### ISSUE TITLE
The Ubuntu package dependencies on 12.10

### ISSUE THREAD

**Issue by zakkak** [hwoarang/pysmssend#2]
Hey guys ;)

the Ubuntu package depends on python2.5\* packages but Ubuntu 12.10 provides python2.7\* packages and up

Not a major
Nice work keep up
Foivos

**Comment by hwoarang** [comment]
Hi,

The ubuntu package is not maintained anymore so this problem is not likely to be fixed in the near future. Feel free to submit a new .deb package if you know how to create one

**Comment by zakkak** [comment]
Since i don't have any packaging experience I will just list the dependencies for Ubuntu 12.10 for the git trunk to work.
- python2.7
- python-mechanize
- python-qt4

`sudo apt-get install python2.7 python-qt4 python-mechanize`

**Comment by clavisound** [comment]
I am not familiar with packaging on ubuntu, but it seems I managed to build it on 13.04

Download the package from here. You can also download the 'packaging script'.
http://clavisound.no-ip.info/htm/tut/nix/deb/index.php

After execution ubuntu-13.04 complains that the application is crashing, but it seems to be working. I managed to send sms.
